### ISSUE TITLE
cusp 2D disturbances runs fail

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemci#2]
```
    Start 181: setup:python:cusp_softprecip2D_Dirich_CI

181: Test command: /Users/zettergm/opt/anaconda3/bin/python3.8 "-m" "gemini3d.model" "/Users/zettergm/Projects/gemci/cfg/daily/cusp_softprecip2D_Dirich_CI" "/Volumes/PegasusR4i/simulations/CI_cases_inputdata/cusp_softprecip2D_Dirich_CI"
181: Environment variables: 
181:  GEMINI_SIMROOT=/Volumes/PegasusR4i/simulations/CI_cases_inputdata
181: Test timeout computed to be: 900
181: Traceback (most recent call last):
181:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
181:     return _run_code(code, main_globals, None,
181:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
181:     exec(code, run_globals)
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 218, in <module>
181:     cli()
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 214, in cli
181:     setup(P.config_file, P.out_dir)
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 140, in setup
181:     interp(cfg)
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 174, in interp
181:     postprocess(cfg, xg)
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 201, in postprocess
181:     Efield_BCs(cfg, xg)
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/efield/__init__.py", line 148, in Efield_BCs
181:     E = func(E, xg, lx1, lx2, lx3, gridflag, flagdip)
181:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/efield/Efield_erf.py", line 66, in Efield_erf
181:     E["Vminx1it"].loc[t] = S * taper
181:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/site-packages/xarray/core/dataarray.py", line 213, in __setitem__
181:     self.data_array[pos_indexers] = value
181:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/site-packages/xarray/core/dataarray.py", line 724, in __setitem__
181:     self.variable[key] = value
181:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/site-packages/xarray/core/variable.py", line 889, in __setitem__
181:     indexable[index_tuple] = value
181:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/site-packages/xarray/core/indexing.py", line 1307, in __setitem__
181:     array[key] = value
181: ValueError: could not broadcast input array from shape (100,1) into shape (1,100)
5/8 Test #181: setup:python:cusp_softprecip2D_Dirich_CI .......***Failed    4.94 sec
```

**Comment by scivision** [comment]
This was fixed in PyGemini
