### ISSUE TITLE
MSIS 2.0 tests fail

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemci#4]
```
    Start 55: setup:python:mini2dns_msis2_eq

55: Test command: /Users/zettergm/opt/anaconda3/bin/python3.8 "-m" "gemini3d.model" "/Users/zettergm/Projects/gemci/cfg/equilibrium/mini2dns_msis2_eq" "/Volumes/PegasusR4i/simulations/CI_cases_inputdata/mini2dns_msis2_eq"
55: Environment variables: 
55:  GEMINI_SIMROOT=/Volumes/PegasusR4i/simulations/CI_cases_inputdata
55: Test timeout computed to be: 900
55: ERROR STOP msis20.parm not found, required by MSIS 2.0
55: Traceback (most recent call last):
55:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
55:     return _run_code(code, main_globals, None,
55:   File "/Users/zettergm/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
55:     exec(code, run_globals)
55:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 218, in <module>
55:     cli()
55:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 214, in cli
55:     setup(P.config_file, P.out_dir)
55:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 142, in setup
55:     equilibrium(cfg)
55:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 158, in equilibrium
55:     dat = equilibrium_state(cfg, xg)
55:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/plasma.py", line 335, in equilibrium_state
55:     atmos = msis_setup(p, xg)
55:   File "/Users/zettergm/Projects/pygemini/src/gemini3d/msis.py", line 98, in msis_setup
55:     raise RuntimeError(
55: RuntimeError: MSIS failed to run: return code 1. See console for additional error info.
1/1 Test #55: setup:python:mini2dns_msis2_eq ...***Failed    1.20 sec
```

**Comment by scivision** [comment]
Gemini3D now outputs a `gemini3d.run -features` string with feature codes. I need to update PyGemini to read those codes. Currently they are written to JSON by GemCI, which is for reproducability.

**Comment by scivision** [comment]
this was enabled in  f4047b8
